# -*- mode: python ; coding: utf-8 -*-
# PyInstaller spec for UConverter — Unit Converter GUI (PySide6)
# Generated by the packaging agent (repo-enhancer) on 2026-06-10.
#
# PyInstaller version: 6.20.0  (research-unit-converter.md, Finding F2.1)
# Python target:       3.13.x  (3.13.13 installed; project requires >=3.11)
# Platform:            Windows (primary); see build_posix.sh for Linux/macOS
#
# Data bundling rationale
# -----------------------
# Two loaders resolve bundled data via sys._MEIPASS:
#
#   unit_converter/core/data_loader.py  ->  _default_data_dir()
#       Returns  Path(sys._MEIPASS) / "unit_converter" / "data"
#       => data files go to dest  "unit_converter/data"
#
#   unit_converter/gui/resources.py  ->  resource_path(rel_path)
#       Returns  os.path.join(sys._MEIPASS, rel_path)
#       logo_path() calls resource_path("Logo UC.png")
#       => logo goes to dest  "."  (bundle root)
#
# Icon note (research L4)
# -----------------------
# PyInstaller --icon requires a .ico file on Windows.  The repo ships
# Logo UC.png.  Run  scripts/png_to_ico.py  once to produce Logo UC.ico,
# then set  icon='Logo UC.ico'  in the EXE block below.  Until the .ico
# exists, set  icon=None  to build without a taskbar icon.
#
# API/server exclusions
# ---------------------
# The GUI bundle does not include FastMCP / FastAPI / uvicorn.  Those are
# excluded explicitly so PyInstaller does not pull them in via transitive
# imports (they live in unit_converter/api/ which is NOT imported by the
# GUI entry point, but explicit exclusion is belt-and-braces).

import sys
from pathlib import Path

# Repo root — resolved relative to this spec file so the spec is portable
# regardless of where PyInstaller is invoked from.
# SPECPATH is the packaging/ directory; the repo root is one level above it.
REPO_ROOT = str(Path(SPECPATH).parent)

block_cipher = None

a = Analysis(
    # Entry point: unit_converter/gui/app.py  (console-script: unit-converter-gui)
    [str(Path(REPO_ROOT) / 'unit_converter' / 'gui' / 'app.py')],
    pathex=[REPO_ROOT],
    binaries=[],
    datas=[
        # Primary unit database (TOML, preferred loader)
        (str(Path(REPO_ROOT) / 'unit_converter' / 'data' / 'magnitudes.toml'),
         'unit_converter/data'),
        # Legacy flat database (backward-compat loader fallback)
        (str(Path(REPO_ROOT) / 'unit_converter' / 'data' / 'Magnitudes.txt'),
         'unit_converter/data'),
        # Application logo — resolved at runtime via resource_path("Logo UC.png")
        (str(Path(REPO_ROOT) / 'Logo UC.png'), '.'),
    ],
    hiddenimports=[
        # PySide6: PyInstaller 6.x ships PySide6 hooks that collect Qt plugins
        # automatically.  These explicit entries guard against edge cases where
        # the platform plugin is not collected by the hook alone.
        'PySide6.QtCore',
        'PySide6.QtGui',
        'PySide6.QtWidgets',
    ],
    hookspath=[],
    hooksconfig={
        # Instruct the bundled PySide6 hook to collect the platform plugin
        # (qwindows.dll on Windows, libqxcb.so on Linux) and Qt image-format
        # plugins (needed to load Logo UC.png at runtime via QPixmap).
        'PySide6': {
            'collect_all': False,
        },
    },
    runtime_hooks=[],
    excludes=[
        # Exclude the access-layer stack — not needed in the GUI bundle.
        'fastmcp',
        'fastapi',
        'uvicorn',
        'starlette',
        'httpx',
        'anyio',
        # Exclude server-only parts of this package.
        'unit_converter.api',
    ],
    noarchive=False,
    cipher=block_cipher,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,      # one-dir mode: binaries go into COLLECT
    name='UConverter',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,              # --windowed / --noconsole: no console window
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    # icon: set to 'Logo UC.ico' after running scripts/png_to_ico.py
    # icon='Logo UC.ico',
    icon=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='UConverter',          # output folder: dist/UConverter/
)
